# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  DAY_OF_WEEK: Funday
  testvar: valueAtWorkflowLevelValue-1
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  mainjob:
    name: 'print environment variables'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env: 
      Greeting: Hello
      testvar: mainjob level value value-2

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: print values of environment variable
        run: |
          echo "$Greeting $First_name. Today is $DAY_OF_WEEK"
          echo "testvar $testvar"
          echo "testvar ${{ env.testvar }}"

        env:
          First_name: Studentname
          testvar: testvalue at step level value-3
  
      # Runs a set of commands using the runners shell
      - name: print environment variables
        run: | 
         echo "$Greeting $First_name. Today is $DAY_OF_WEEK"
         echo "testvar $testvar"