name: Github environments secrets

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest    
    
    environment: 
      name: PROD
      url: http://github.com
        
    steps:
      - name: 'fetch the prod first secret'
        run: |
          echo "PROD_SECRET: ${{ secrets.PROD_SECRET1 }}"