# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "build step"

  build-app:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: single line script  
      run: echo build job single line

    - name: multiple line script
      run: |
       echo first line
       echo secong line


  build-db:
    needs: build-app
    
    runs-on: macos-latest
    steps:
    - name: build test app
      run: echo build on mac os
    - name: packaging test app
      run: echo testing app  

  package-app:
    needs: [build-app,build-db]
    runs-on: windows-latest
    steps:
      - name: packaing
        run: echo packaing build app and db app   

