name: github secrets
# Controls when the workflow will run
on:
 
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  fetching_secret:
   
    runs-on: ubuntu-latest
    steps: 
    - name: print secret    
      run: |
        echo "SECRET1: ${{ secrets.MY_SECRET}}"
        echo "SECRET2: ${{ secrets.MY_SECRET2}}"
    - name: use secret as environment
      run: |
        echo "SECRET1: $SECRET1"
      env:
          echo "ENV_SECRET: $SECRET1"